In [65]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [66]:
lfpl_df = pd.read_csv("Louisville_Metro_KY_-_Library_Collection_Inventory.csv")

In [67]:
pd.options.display.float_format = '{:.0f}'.format

In [68]:
lfpl_df.head()

,BibNum,Title,Author,ISBN,PublicationYear,ItemType,ItemCollection,ItemLocation,ItemPrice,ReportDate,ObjectId
0,707409,"Jeff Immelt and the new GE way : innovation, t...","Magee, David, 1965-",9780071605878,2009,Book,Adult Non-Fiction,Main,26,2022/07/01 04:00:00+00,1
1,1341361,McGraw-Hill's American idioms dictionary,"Spears, Richard A.",9780071478939,2007,Book,ELL Collection,South Central,20,2022/07/01 04:00:00+00,2
2,707411,Robin rescues dinner : 52 weeks of quick-fix m...,"Miller, Robin, 1964-",9780307451408,2009,Book,Adult Non-Fiction,Southwest,20,2022/07/01 04:00:00+00,3
3,1341362,McGraw-Hill's essential ESL grammar : a handbo...,"Lester, Mark.",9780071496421,2008,Book,ELL Collection,South Central,20,2022/07/01 04:00:00+00,4
4,707411,Robin rescues dinner : 52 weeks of quick-fix m...,"Miller, Robin, 1964-",9780307451408,2009,Book,Adult Non-Fiction,Southwest,20,2022/07/01 04:00:00+00,5

In [69]:
lfpl_df.dtypes

BibNum               int64
Title               object
Author              object
ISBN               float64
PublicationYear      int64
ItemType            object
ItemCollection      object
ItemLocation        object
ItemPrice          float64
ReportDate          object
ObjectId             int64
dtype: object

In [70]:
lfpl_df.isnull().sum()*100/len(lfpl_df)

BibNum             0
Title              0
Author            12
ISBN              14
PublicationYear    0
ItemType           0
ItemCollection     0
ItemLocation       0
ItemPrice          0
ReportDate         0
ObjectId           0
dtype: float64

In [80]:
lfpl_df['ItemLocation'].unique()

array(['Main', 'South Central', 'Southwest', 'Remote Shelving - Main',
       'Iroquois', 'Newburg', 'Shively', 'Bon Air', 'St Matthews',
       'Northeast', 'Fairdale', 'Middletown', 'Jeffersontown', 'Shawnee',
       'Highlands - Shelby Park', 'Crescent Hill', 'Portland', 'Western',
       'Remote Shelving - Shawnee', 'Childrens Main Library', 'Main Teen',
       'Childrens Bookmobile', 'Adult Bookmobile', 'Content Management'],
      dtype=object)

In [79]:
counts = lfpl_df.groupby('ItemCollection').size().reset_index(name = 'Count')
counts

             ItemCollection   Count
0           Adult Audiobook   43564
1             Adult Blu-Ray    3419
2                 Adult DVD   46694
3             Adult Fiction  173481
4         Adult Non-Fiction  372781
..                      ...     ...
59            Urban Fiction    7556
60                  Western    2137
61  Younger Teen  Audiobook    1454
62    Younger Teen  Fiction   17227
63  Younger Teen  Paperback     647

[64 rows x 2 columns]